### ISSUE TITLE
Make .Reply() and friends split the message when it's too long

### ISSUE THREAD

**Issue by belak** [belak/irc#5]

**Comment by Xe** [comment]
In the past I have found that a sane limit is 450 characters.

**Comment by belak** [comment]
I've gone back and forth on this, trying to decide if this should be done or not. My current opinion is to add another method which would handle splitting, but that may start to get fairly complicated due to having so many `.Reply` methods.

```
func (c *Client) Reply(e *Event, format string, v ...interface{}) error
func (c *Client) MentionReply(e *Event, format string, v ...interface{}) error

// These would be added (or something like these
func (c *Client) SplitReply(e *Event, format string, v ...interface{}) error
func (c *Client) SplitMentionReply(e *Event, format string, v ...interface{}) error

```

Opinions? Ways it could be done better?

**Comment by Xe** [comment]
Maybe some kind of configuration setting to automatically split?

**Comment by belak** [comment]
I think the ideal solution to this would to implement this as an output handler as soon as #2 is solved

**Comment by belak** [comment]
Because #2 was closed, I think this would be better handled elsewhere so this package can stay as simple as possible.
