### ISSUE TITLE
Identity.Copy() doesn't copy anything other than a reference

### ISSUE THREAD

**Issue by Xe** [belak/irc#6]
```go
func (i *Identity) Copy() *Identity {
    newIdent := &Identity{}

    *newIdent = *i

    return newIdent
}
```

**Comment by belak** [comment]
I'm pretty sure this does actually copy it. `i` is dereferenced and copied. Both copy methods use this trick.

http://play.golang.org/p/GAwTC7nSs0

However, it's definitely not very clear how it works. I can look into changing that.

**Comment by belak** [comment]
I'm going to close this for now, but feel free to reopen this if you can verify it's not actually copying.
